name: mini_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: 4.6.6
  firebase_core: 3.0.0
  firebase_auth: 5.0.0
  cloud_firestore: 5.0.0
  get_storage: 2.1.1
  cached_network_image: 3.3.1
  firebase_storage: 12.0.0
  image_picker: 1.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/Bg-Splash Screen.png
    - assets/Bg-Login Register.png
    - assets/Bg-Home Screen.png
    - assets/bunga.png
    - assets/gbr-login.png
  uses-material-design: true

